-- -----------------------> AGGREAGE OPERATORS <-------------------------------
-- 1. COUNT 

SELECT COUNT(STD_ID) AS AGE_EQUALS_TO_23 FROM STD WHERE AGE = 23;

-- 2. MAX 
SELECT MAX(MARKS) AS STD_MAX_MARKS FROM STD;

-- 3. MIN 

SELECT MIN(MARKS) AS STD_MIN_MARKS FROM STD;

-- 4. SUM 

SELECT  SUM(MARKS) AS TOTAL_STD_MARKS FROM STD;

-- 5. AVG 

SELECT AVG(MARKS) AS AVERAGE_MARKS FROM STD;

-- 6. DISTINCT
 
SELECT  DISTINCT NAME FROM STD;

-- ------------------------> AGGREGATE FUNCTIONS WITH WHERE CLAUSE <--------------------------

SELECT COUNT(MARKS) AS MARKS_GREATER_1000 FROM STD WHERE MARKS > 1000;

SELECT * FROM STD;