-- DATA BASE CREATION 
CREATE DATABASE RGM;

-- ACTIVATING DATABASE 
USE RGM;
-- CREATING A TABLE 
CREATE TABLE STUDENT( 
STUDENT_ID INT PRIMARY KEY NOT NULL,
STUDENT_NAME VARCHAR(30) NOT NULL,
GENDER VARCHAR(2) NOT NULL,
STUDENT_MARKS INT NOT NULL,
STUDENT_RANK INT NOT NULL
);

-- RENAMING THE COLUMN NAMES 

ALTER TABLE STUDENT RENAME COLUMN STUDENT_MARKS TO RGM_STUDNET_MARKS;

-- CHANGING THE TABLE NAME 

ALTER TABLE RGM_STUDNET RENAME TO RGM_STUDENT;

-- MODIFYING THE COLUMN DATA TYPE 

ALTER TABLE RGM_STUDENT
MODIFY COLUMN STUDENT_RANK VARCHAR(45);

-- ADDING A NEW ATTRIBUTE TO THE EXISTING TABLE 

ALTER TABLE RGM_STUDENT 
ADD ADDRESS VARCHAR(30);

-- REMOVING THE COLUMN FROM EXISTING TABLE 

ALTER TABLE RGM_STUDENT 
DROP ADDRESS;

-- REMOVING THE RECORDS IN THE EXISTING TABLE 
-- TRUNCATE TABLE RGM_STUDENT; 

-- TO REMOVE ENTIRE TABLE INCLUDING SCHEMA 

DROP TABLE RGM_STUDENT;

-- TO REMOVE DATABASE 

DROP DATABASE RGM;

-- DATA DEFINITION LANGUGE(DDL) COMMANDS 
-- CREATE 
-- DROP 
-- ALTER 
	-- 1. RENAME 
	-- 2. MODIFY 
    -- 3. ADD 
    -- 4. DROP 
-- TRUNCATE 


