-- ------------------------> PRIMARY KEY <----------------------------------------
-- CREATING A NEW TABLE WITH THE NAME OF STD_TABLE 

CREATE TABLE STD_TABLE(
ID INT PRIMARY KEY, -- It only accepts the unique values 
NAME VARCHAR(30),
GMAIL VARCHAR(30),
AGE INT
);



-- INSERTING THE DATA INTO THE TABLE CALLED STD_TABLE 

INSERT INTO STD_TABLE VALUES 
(201,"RAVI","ABC@GMAI.COM",22),
(202,"HARI","XYZ@GMAIL.COM",33),
(203,"ANWAR","ASD@GMAIL.COM",44),
(204,"BASHA","BASHA@GMAIL.COM",77),
(205,"ROHITH","ROHITH@MAIL.COM",99);

-- ---------------------> FOREIGN KEY <-------------------------------- 
-- CREATE A NEW TABLE WITH THE NAME OF CERTIFICATE 

CREATE TABLE CERTIFICATE(
ID INT ,
CERTIFICATES INT,
SEMESTER INT,
 FOREIGN KEY (ID) REFERENCES STD_TABLE(ID)
);

-- INSERTING THE DATA INTO CERTIFICATE TABLE 

INSERT INTO CERTIFICATE VALUES 
(201,3,4),
(202,7,3),
(203,2,2),
(204,5,2),
(205,5,7);

-- --------------------------> CONSTRAINTS <--------------------------------
-- 1. NOT NULL
-- 2. UNIQUE 
-- 3. CHECK 
-- 4. AUTO_INCREMENT

-- CREATING A NEW TABLE WITH THE NAME OF CERTIFICATE_LOG 

CREATE TABLE CERTIFICATE_LOG(
ID INT NOT NULL AUTO_INCREMENT,
NAME VARCHAR(30),
CERTIFICATES INT NOT NULL,
DATE_ DATE ,
FOREIGN KEY (ID) REFERENCES STD_TABLE(ID),
CHECK(CERTIFICATES>1),
UNIQUE (NAME)
);

-- ASSIGNING THE AUTO_INCREMENT VALUE TO START FROM 201 

ALTER TABLE CERTIFICATE_LOG 
AUTO_INCREMENT = 201;

DROP TABLE CERTIFICATE_LOG;
-- INSERTING THE DATA INTO CERTIFICATE_LOG TALBE 

INSERT INTO CERTIFICATE_LOG (NAME,CERTIFICATES,DATE_) VALUES 
("RAVI",4,'2023-01-04'),
("ANWAR",7,'2022-03-22'),
("ROHITH",2,'2021-09-10');

SELECT * FROM CERTIFICATE_LOG;



